apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: techsummit-ingress
spec:
  rules:
  - host: sample-php.techsummit
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd
          servicePort: 8080
