# From:
#  https://kubernetes.io/docs/tutorials/stateless-application/guestbook/
version: '3'
services:
  guestbook:
    build: .
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - 8080:80
    links:
      - redismaster:redis-master
      - redisslave:redis-slave
  redismaster:
    image: k8s.gcr.io/redis:e2e
    ports:
      - 3001:6379
  redisslave:
    image: gcr.io/google_samples/gb-redisslave:v3
    links:
      - redismaster:redis-master
    ports:
      - 3002:6379
