apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: techsummit-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: sample-php.techsummit
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd
          servicePort: 8080
  - host: guestbook.techsummit
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
